import DropshotPreview from "@/assets/c-dropshot-prev.webp";
import P2Preview from "@/assets/c-p2p.webp";
import TeamzPreview from "@/assets/c-teamz.webp";
import VigiePreview from "@/assets/c-vigie.png";
import WetennixPreview from "@/assets/c-wetennix.webp";
import VoilaPreview from "@/assets/c-voila.webp";
import type { ImageMetadata } from "astro";

import type { LocalizedList, LocalizedText } from "@/i18n/ui";

export type CaseStudy = {
  slug: string;
  title: string;
  url?: string;
  image?: ImageMetadata;
  accent: string;
  tagline: LocalizedText;
  context: LocalizedText;
  role: LocalizedText;
  decisions?: LocalizedList;
  highlights: LocalizedList;
  stack: string[];
};

export const caseStudies: CaseStudy[] = [
  {
    slug: "dropshot-coaching",
    title: "Dropshot Coaching",
    url: "https://dropshot-coaching.com/",
    image: DropshotPreview,
    accent: "#a3e635",
    tagline: {
      en: "AI video coaching for tennis players",
      fr: "Coaching vidéo tennis par IA",
    },
    context: {
      en: "A platform where tennis players film their strokes and receive AI-generated technical analysis and personalized coaching. Mobile app for players, web backoffice for admins.",
      fr: "Une plateforme où les joueurs de tennis filment leurs gestes et reçoivent une analyse technique par IA et un coaching personnalisé. App mobile pour les joueurs, backoffice web pour les admins.",
    },
    role: {
      en: "Full development of the mobile app, the admin web app and the whole content chain: videos, generated copy and translations, frame extraction for thumbnails, lesson recommendations. The video analysis (player angle, recommendations based on tennis metrics) was built by the [IA LAB](https://ia-lab.fr/) studio, in close collaboration throughout the project.",
      fr: "Développement complet de l'app mobile, de l'admin web et de toute la chaîne de contenu : vidéos, textes et traductions générés, extraction des frames pour les thumbnails, recommandation de leçons. L'analyse vidéo (angle du joueur, recommandations basées sur les métriques du tennis) a été développée par le studio [IA LAB](https://ia-lab.fr/), en collaboration continue tout au long du projet.",
    },
    decisions: {
      en: [
        "Designed the 4-step coaching pipeline (AI analysis, frame extraction, coaching generation, delivery) with per-step retries and a cron safety net",
        "Coaching text generated by Claude with structured output, using the player's last 3 sessions as context",
        "Build-vs-buy R&D on multilingual video dubbing, documented with the trade-offs so the client could decide",
      ],
      fr: [
        "Conception du pipeline de coaching en 4 étapes (analyse IA, extraction de frames, génération du coaching, livraison) avec retries par étape et filet de sécurité cron",
        "Texte de coaching généré par Claude en sortie structurée, avec les 3 dernières sessions du joueur en contexte",
        "R&D build-vs-buy sur le dubbing vidéo multilingue, documentée avec les trade-offs pour laisser le client trancher",
      ],
    },
    highlights: {
      en: [
        "AI video analysis pipeline in production, with push notifications on completion",
        "Lesson recommendations powered by a vector database",
        "Mobile subscriptions via RevenueCat",
        "3 languages (FR, EN, ES), with the coaching generated in the user's language",
        "Monorepo Turborepo: Expo app, React backoffice, Convex backend, CI per app",
        "Mobile app currently rolling out to the stores",
      ],
      fr: [
        "Pipeline d'analyse vidéo IA en production, notifications push en fin de traitement",
        "Recommandation de leçons via base de données vectorielle",
        "Abonnements mobiles via RevenueCat",
        "3 langues (FR, EN, ES), avec le coaching généré dans la langue de l'utilisateur",
        "Monorepo Turborepo : app Expo, backoffice React, backend Convex, CI par app",
        "App mobile en cours de déploiement sur les stores",
      ],
    },
    stack: [
      "TypeScript",
      "Expo",
      "React",
      "TanStack Router",
      "Convex",
      "Claude API",
      "RevenueCat",
      "Cloudflare",
    ],
  },
  {
    slug: "wetennix",
    title: "WeTennix",
    image: WetennixPreview,
    accent: "#facc15",
    tagline: {
      en: "Fantasy tennis game on web and mobile",
      fr: "Fantasy game tennis sur web et mobile",
    },
    context: {
      en: "A fantasy tennis game: users build a team of real ATP/WTA players for real tournaments, apply bonuses, score points from real results and compete in leagues. Public product on mobile, admin console on web.",
      fr: "Un fantasy game tennis : les utilisateurs composent une équipe de vrais joueurs ATP/WTA pour de vrais tournois, appliquent des bonus, marquent des points selon les résultats réels et s'affrontent en ligues. Produit grand public sur mobile, console admin sur web.",
    },
    role: {
      en: "Complete takeover of an existing product, already live with its users: migrating the whole stack and the accounts, rebuilding the game logic, shipping a new mobile app and automating the tennis data ingestion. An end-to-end scope, from the database to the mobile app.",
      fr: "Reprise complète d'un produit existant, déjà en production avec ses utilisateurs : migration de toute la stack et des comptes, refonte de la logique de jeu, nouvelle app mobile et ingestion automatisée des données tennis. Un périmètre de bout en bout, de la base de données jusqu'à l'app mobile.",
    },
    decisions: {
      en: [
        "Project taken over from a Firebase V1 with an Ionic/Angular mobile app built on Capacitor, fully migrated to a Node, tRPC and PostgreSQL stack",
        "Existing users carried over without friction: V1 accounts move to the new auth system with no password reset",
        "Documented benchmarks of tennis data sources before choosing the scraping strategy",
        "V2 now in development: a new game mode, richer content and a monetization system",
      ],
      fr: [
        "Projet repris d'une V1 Firebase avec une app mobile Ionic/Angular sous Capacitor, entièrement migré vers une stack Node, tRPC et PostgreSQL",
        "Utilisateurs existants embarqués sans friction : les comptes de la V1 basculent vers le nouveau système d'auth sans reset de mot de passe",
        "Benchmarks documentés des sources de données tennis avant de choisir la stratégie de scraping",
        "V2 en cours de développement : nouveau mode de jeu, contenu enrichi et système de monétisation",
      ],
    },
    highlights: {
      en: [
        "Monorepo with 4 apps (web, mobile, API, marketing) plus a Python scraper in production",
        "Jobs, crons and scraping powering the tennis data ingestion",
        "Mobile app built with Expo, deployed through EAS",
        "Web deployed on Cloudflare Workers, API on Railway, tests colocated in 3 workspaces",
      ],
      fr: [
        "Monorepo de 4 apps (web, mobile, API, marketing) plus un scraper Python en production",
        "Jobs, crons et scraping pour l'ingestion des données tennis",
        "App mobile Expo, déployée via EAS",
        "Web déployé sur Cloudflare Workers, API sur Railway, tests colocalisés dans 3 workspaces",
      ],
    },
    stack: [
      "TypeScript",
      "React 19",
      "TanStack Router",
      "Expo",
      "Hono",
      "tRPC",
      "Drizzle",
      "Neon",
      "Astro",
      "Cloudflare",
    ],
  },
  {
    slug: "teamz-tennis",
    title: "Teamz Tennis",
    url: "https://www.teamz-tennis.com/",
    image: TeamzPreview,
    accent: "#FE5000",
    tagline: {
      en: "The marketplace connecting the tennis world",
      fr: "La marketplace qui connecte le monde du tennis",
    },
    context: {
      en: "Teamz connects tennis organizations with players and coaches: recruitment listings, applications, messaging, tournaments. The first version, launched two years ago, matched clubs and players. The V2 currently in development opens the platform to padel, coach profiles and new kinds of organizations: hotels, resorts, federations.",
      fr: "Teamz met en relation les structures du tennis avec les joueurs et les coachs : annonces de recrutement, candidatures, messagerie, tournois. La première version, lancée il y a deux ans, connectait clubs et joueurs. La V2 en cours de développement ouvre la plateforme au padel, aux profils coach et à de nouveaux types de structures : hôtels, resorts, fédérations.",
    },
    role: {
      en: "Fullstack development over the long run: the V1 two years ago, now the V2 with the API migration from Hono RPC to tRPC, coach profiles, padel and the freemium plans. Plus Stripe payments and a security audit along the way.",
      fr: "Développement fullstack sur la durée : la V1 il y a deux ans, aujourd'hui la V2 avec la migration de l'API de Hono RPC vers tRPC, les profils coach, le padel et le freemium. S'y ajoutent les paiements Stripe et un audit de sécurité au passage.",
    },
    decisions: {
      en: [
        "V2 designed as a widening of the domain: padel, coach profiles, and organizations beyond clubs (hotels, resorts, federations)",
        "API migration from Hono RPC to tRPC v11, written down as a design spec before any code",
      ],
      fr: [
        "V2 pensée comme un élargissement du domaine : padel, profils coach, et des structures au-delà des clubs (hôtels, resorts, fédérations)",
        "Migration de l'API de Hono RPC vers tRPC v11, posée dans une design spec avant d'écrire le code",
      ],
    },
    highlights: {
      en: [
        "Stripe freemium plans, checkout and billing portal, signed webhooks (Stripe, Clerk, StreamChat)",
        "Real-time messaging with Stream Chat",
        "Full admin area: managing players, coaches and organizations, reports and moderation, supporting a managed offer where the Teamz team runs the search for coaches and players on behalf of organizations",
        "V2 roadmap driven milestone by milestone on Linear (padel, coach, freemium, back office)",
        "10 tRPC routers, ~25 web routes, preview deployments behind a dedicated proxy",
        "End-to-end type safety: the web app only imports the emitted API types",
      ],
      fr: [
        "Plans freemium Stripe, checkout et portail de facturation, webhooks signés (Stripe, Clerk, StreamChat)",
        "Messagerie temps réel avec Stream Chat",
        "Partie admin complète : gestion des joueurs, coachs et structures, signalements et modération, en soutien d'une offre pilotée où l'équipe Teamz gère la recherche de coachs et de joueurs pour les structures",
        "Roadmap V2 pilotée milestone par milestone sur Linear (padel, coach, freemium, back office)",
        "10 routers tRPC, ~25 routes web, preview deployments derrière un proxy dédié",
        "Type-safety end-to-end : le web n'importe que les types émis par l'API",
      ],
    },
    stack: [
      "TypeScript",
      "Bun",
      "React 19",
      "tRPC",
      "Hono",
      "Drizzle",
      "Neon",
      "Stripe",
      "Fly.io",
    ],
  },
  {
    slug: "voila-esim",
    title: "voilà eSIM",
    url: "https://voilacreators.com/",
    image: VoilaPreview,
    accent: "#fc3838",
    tagline: {
      en: "Visual overhaul of the creator dashboard",
      fr: "Refonte visuelle du dashboard créateurs",
    },
    context: {
      en: "voilà is a travel app now focused on international eSIMs, trusted by more than 100,000 travelers. At the time of the mission, the product still revolved around travel guides written by creators: the team needed a visual overhaul of the creator dashboard, the space where a creator builds a guide, translates it into several languages and adds their recommendations, before the product later refocused on eSIMs.",
      fr: "voilà est une app de voyage aujourd'hui centrée sur les eSIM internationales, utilisée par plus de 100 000 voyageurs. Au moment de la mission, le produit tournait encore autour de guides de voyage rédigés par des créateurs : l'équipe avait besoin d'une refonte visuelle du dashboard créateurs, l'espace où un créateur compose son guide, le traduit en plusieurs langues et y ajoute ses recommandations, avant le recentrage du produit sur l'eSIM.",
    },
    role: {
      en: "A front-end mission within a team already in place: full visual overhaul of the creator dashboard, with every screen wired to the existing tRPC API, delivered on time and within the agreed scope. The stack was close to a familiar one, but the conventions, tooling and ways of working were the team's own.",
      fr: "Mission front au sein d'une équipe déjà en place : refonte visuelle complète du dashboard créateurs, avec le branchement des écrans sur l'API tRPC existante, livrée dans les délais et le périmètre convenus. La stack était proche d'un terrain connu, mais les conventions, l'outillage et la façon de travailler étaient ceux de l'équipe.",
    },
    highlights: {
      en: [
        "Quick ramp-up in an existing codebase, following the team's conventions and workflows",
        "Guide creation flow rebuilt end-to-end: writing, translations, recommendations",
        "Mission delivered on schedule, without scope creep",
        "Adapting to the team's processes and work habits",
      ],
      fr: [
        "Montée en route rapide dans une codebase existante, en suivant les conventions et le workflow de l'équipe",
        "Parcours de création de guide refondu de bout en bout : rédaction, traductions, recommandations",
        "Mission livrée dans les temps, sans dérive de périmètre",
        "Adaptation aux process et aux habitudes de travail de l'équipe",
      ],
    },
    stack: ["TypeScript", "React", "tRPC", "shadcn/ui", "Tailwind"],
  },
  {
    slug: "peer2park",
    title: "Peer2Park",
    url: "https://peer2parkdubai.com/",
    image: P2Preview,
    accent: "#8aa5f6",
    tagline: {
      en: "P2P parking marketplace in Dubai",
      fr: "Marketplace P2P de parking à Dubaï",
    },
    context: {
      en: "A peer-to-peer marketplace connecting parking space owners and renters in Dubai: verified listings, location-based search, paid listing boosts.",
      fr: "Une marketplace peer-to-peer entre propriétaires et locataires de places de parking à Dubaï : annonces vérifiées, recherche par localisation, boosts d'annonces payants.",
    },
    role: {
      en: "Fullstack development of the whole product, structured in domain modules: auth, listings, payment, user.",
      fr: "Développement fullstack de l'ensemble du produit, structuré en modules par domaine métier : auth, annonces, paiement, utilisateur.",
    },
    decisions: {
      en: [
        "Full-stack SSR with React Router 7 as framework, tRPC end-to-end",
        "Payment flow driven by Stripe, activating listings and boosts once the payment is confirmed",
        "Listings moderated before going live: a moderator is notified, checks that the listing is genuine and decides on publication, a level of scrutiny required by Dubai's strict content rules",
        "Domain-driven folder architecture to keep business logic navigable",
      ],
      fr: [
        "SSR full-stack avec React Router 7 en framework, tRPC end-to-end",
        "Flux de paiement piloté par Stripe, avec activation des annonces et des boosts une fois le paiement confirmé",
        "Modération des annonces avant mise en ligne : un modérateur est prévenu, vérifie la véracité de l'annonce et décide de sa publication, un niveau d'exigence imposé par les règles strictes de Dubaï en matière de contenu",
        "Architecture par domaines métier pour garder la logique business navigable",
      ],
    },
    highlights: {
      en: [
        "Complete Stripe integration",
        "Bilingual English / Arabic with full RTL support",
        "Google Maps integration, image uploads with HEIC support",
        "Deployed on Fly.io with preview environments",
      ],
      fr: [
        "Intégration Stripe complète",
        "Bilingue anglais / arabe avec support RTL complet",
        "Intégration Google Maps, upload d'images avec support HEIC",
        "Déployé sur Fly.io avec environnements de preview",
      ],
    },
    stack: [
      "TypeScript",
      "React Router 7",
      "tRPC",
      "Drizzle",
      "PostgreSQL",
      "Stripe",
      "i18next",
      "Fly.io",
    ],
  },
  {
    slug: "vigie",
    title: "Vigie",
    url: "https://github.com/ArthurSalle/vigie",
    image: VigiePreview,
    accent: "#a78bfa",
    tagline: {
      en: "Native macOS menu-bar app for dev ports",
      fr: "App macOS native de surveillance des ports",
    },
    context: {
      en: "A native macOS menu-bar app that watches listening TCP ports and reminds you to kill forgotten dev servers. Built for the AI-coding era, where agents spawn servers nobody remembers to stop.",
      fr: "Une app macOS native (barre de menus) qui surveille les ports TCP en écoute et rappelle de tuer les serveurs de dev oubliés. Pensée pour l'ère du code assisté par IA, où les agents lancent des serveurs que personne n'arrête.",
    },
    role: {
      en: "A small personal project whose Swift code is entirely AI-generated, driven by specs and iterations rather than written by hand. Born out of a real annoyance, a few forgotten dev servers running in the background, and turned into a demonstration of what can be shipped by driving AI agents outside one's own stack. A tool for the AI-coding era, itself coded by AI.",
      fr: "Petit projet perso dont le code Swift est entièrement généré par IA, guidé par des specs et des itérations plutôt qu'écrit à la main. Né d'un agacement concret, quelques serveurs de dev oubliés en fond, et devenu une démonstration de ce qu'on peut livrer en pilotant des agents IA hors de sa propre stack. Un outil pour l'ère du code assisté par IA, lui-même codé par IA.",
    },
    decisions: {
      en: [
        "100% local and private: no network calls, no telemetry, no root privileges",
        "Detects which AI agent or terminal spawned each process by walking the parent chain",
        "Graceful kill strategy (SIGTERM then SIGKILL), system processes locked",
      ],
      fr: [
        "100% local et privé : aucun appel réseau, zéro télémétrie, pas de privilèges root",
        "Détecte quel agent IA ou terminal a lancé chaque process en remontant la chaîne parent",
        "Kill gracieux (SIGTERM puis SIGKILL), process système verrouillés",
      ],
    },
    highlights: {
      en: [
        "Swift 6 / SwiftUI, zero external dependencies, built with SwiftPM",
        "Native notifications with inline Kill / Ignore actions",
        "Near real-time rescan (5s), stale-port reminders, network-exposure warnings",
        "CLI mode for scripting the scanner without the UI",
      ],
      fr: [
        "Swift 6 / SwiftUI, zéro dépendance externe, build SwiftPM",
        "Notifications natives avec actions inline Kill / Ignore",
        "Rescan quasi temps réel (5 s), rappels de ports anciens, alertes d'exposition réseau",
        "Mode CLI pour scripter le scanner sans l'UI",
      ],
    },
    stack: ["Swift 6", "SwiftUI", "SwiftPM", "macOS"],
  },
];
